### ISSUE TITLE
html-select failing on &gt;img/>

### ISSUE THREAD

**Issue by 007design** [substack/node-trumpet#38]
It looks like you recently switched from using the SAX parser to html-select.  However, it appears that image tags with trailing slashes like so:
&lt;img src="whatever.jpg"/>
cause an issue.
It looks as if html-select is seeing the slash as another argument, probably as a result of a regex used to split the string.  Regardless, because the slash isn't an attribute when it's "value" is parsed using string.replace() it fails.

**Comment by kouk** [comment]
I think this has been fixed in recent versions. Are you still seeing this?
